apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: g3rbflvrp-python 
  janus-idp.io/tekton: g3rbflvrp-python
  backstage.io/kubernetes-id: g3rbflvrp-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: g3rbflvrp-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml